### ISSUE TITLE
Julian on Argentina for HTML to Markdown

### ISSUE THREAD

**Issue by shanecoughlan** [crypto-law-survey/crypto-law-survey#12]
https://github.com/crypto-law-survey/crypto-law-survey/blob/main/data/countries/argentina.md

@juliancoccia

**Comment by juliancoccia** [comment]
I've emailed the _Direccion de Seguridad Internacional, Asuntos Nucleares y Espaciales_ from the _Ministerio de Relaciones Exteriores, Comercio Internacional y Culto_ (http://www.mrecic.gov.ar/). I'll post an update when I get a response

**Comment by juliancoccia** [comment]
@stephenkilbaneadi is there anything else to be done to the formatting? It looks good to me as it is.

**Comment by juliancoccia** [comment]
> I've emailed the _Direccion de Seguridad Internacional, Asuntos Nucleares y Espaciales_ from the _Ministerio de Relaciones Exteriores, Comercio Internacional y Culto_ (http://www.mrecic.gov.ar/). I'll post an update when I get a response

Got a response from the "Directorate of International Security, Nuclear and Space Affairs
Ministry of Foreign Affairs, International Trade and Worship" redirecting my inquiry to the "National Commission for the Control of Sensitive Exports and War Material (CONCESYMB)". I sent a follow up email but I did not get a response yet. 

The URL to that agency is: 
https://www.argentina.gob.ar/defensa/comision-nacional-de-control-de-exportaciones-sensitivas-y-material-belico-concesymb

The first paragraph in that website reads: "In accordance with Decree 603/92, its amending and complementary regulations, the National Commission for the Control of Sensitive Exports and War Material (CONCESYMB) controls exports of sensitive and war material in compliance with the international commitments made by the Argentine Republic regarding non-compliance. proliferation of weapons of mass destruction and their delivery systems."

This makes me believe there are no trade regulations related to cryptography in non-war materials, but I can't confirm until I get a response from the agency.

**Comment by shanecoughlan** [comment]
Flagged by Julian as done in terms of formatting, issue being closed.
