### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by stephenkilbaneadi** [crypto-law-survey/crypto-law-survey#2]
We should add a CONTRIBUTING.md file to the root of the repo, to set expectations and encourage contributions.

For background, see https://patterns.innersourcecommons.org/p/base-documentation

**Comment by gravax** [comment]
I like the idea. And then we link to it from the "Participate" section in the main README.md.

Do you want to take a first stab?

**Comment by gravax** [comment]
Actually, I have created a very basic version.

**Comment by stephenkilbaneadi** [comment]
Nice!

**Comment by gravax** [comment]
We can close this issue.
